# Generated by Django 5.1.15 on 2026-06-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('principal_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogDocument',
            fields=[
                ('subject', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RemediationMaterial',
            fields=[
                ('material_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='science', max_length=20)),
                ('original_topic_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('created_quiz', models.JSONField(default=list)),
                ('publish_date', models.CharField(max_length=20)),
                ('target_section', models.CharField(max_length=80)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('lrn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('grade_level', models.CharField(max_length=80)),
                ('section', models.CharField(max_length=80)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(default='General Academics', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=40)),
                ('lesson_id', models.CharField(blank=True, default='', max_length=40)),
                ('score', models.IntegerField()),
                ('perfect_score', models.IntegerField(default=3)),
                ('answers', models.JSONField(default=list)),
                ('completed_at', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='wave_api.student')),
            ],
            options={
                'unique_together': {('student', 'topic_id')},
            },
        ),
        migrations.CreateModel(
            name='SummativeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField(default=20)),
                ('percent', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, default='')),
                ('failed_items', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summatives', to='wave_api.student')),
            ],
            options={
                'unique_together': {('student', 'lesson_id')},
            },
        ),
    ]
