# Generated by Django 5.1.15 on 2026-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='perfect_score',
            field=models.IntegerField(default=10),
        ),
    ]
