# Generated by Django 5.1.15 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0003_summativeresult_attempts_remediationmaterial_created_summative'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='password123', max_length=40),
        ),
    ]
