# Generated by Django 5.1.15 on 2026-06-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0005_remediationmaterial_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remediationmaterial',
            name='assigned_student_lrn',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='remediationmaterial',
            name='target_lesson_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
