# Generated by Django 5.1.15 on 2026-06-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0006_quizattempt_attempts'),
        ('wave_api', '0006_quizattempt_attempts_and_more'),
    ]

    operations = [
    ]
