# Generated by Django 5.1.15 on 2026-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0007_merge_20260621_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationmaterial',
            name='concepts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='remediationmaterial',
            name='grade_level_section',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='remediationmaterial',
            name='learning_gap',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='remediationmaterial',
            name='lesson_number',
            field=models.IntegerField(default=0),
        ),
    ]
