# Generated by Django 5.1.15 on 2026-06-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave_api', '0008_remediationmaterial_concepts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediationmaterial',
            name='created_quiz',
        ),
    ]
