"""
GENERATED by protocol/codegen/generate.mjs from protocol/wire_manifest.json.
DO NOT EDIT BY HAND. Run `npm run codegen` after changing the manifest.

Pydantic mirrors of the canonical wire models. Field aliases are camelCase
so `.model_dump(by_alias=True)` round-trips cleanly through
`codec.encode(...)`. Agent-internal shapes (diagnosis, evaluator output,
letter-keyed options) are deliberately NOT mirrored here — they never reach
MQTT/LoRa.
"""
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class WireStudentQuizAttempt(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    topic_id: str = Field(alias="topicId")
    score: int
    perfect_score: int = Field(alias="perfectScore")
    answers: List[int] = Field(default_factory=list)
    completed_at: str = Field(alias="completedAt")

class WireQuizScore(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    score: int
    total: int
    percent: int
    passed: bool

class WireSummativeScore(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    score: int
    perfect_score: int = Field(alias="perfectScore")
    feedback: str
    attempts: Optional[int] = Field(default=None)

class WireFailedItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    question_id: str = Field(alias="questionId")
    topic_id: str = Field(alias="topicId")
    selected_option: int = Field(alias="selectedOption")
    correct_option: int = Field(alias="correctOption")

class WireStanding(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    rank: int
    student_lrn: str = Field(alias="studentLrn")
    name: str
    score: int
    perfect: int
    percent: int

class WireQuizQuestion(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    question: str
    options: List[str] = Field(default_factory=list)
    correct_answer_index: int = Field(alias="correctAnswerIndex")
    explanation: str

class WireChunk(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    index: int
    total: int
    data: str

class WireSummativeConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total: int
    pass_mark: int = Field(alias="passMark")
    items_per_topic: Optional[int] = Field(default=None, alias="itemsPerTopic")
    shuffle_options: Optional[bool] = Field(default=None, alias="shuffleOptions")
    shuffle_questions: Optional[bool] = Field(default=None, alias="shuffleQuestions")
    template_ids: Optional[List[str]] = Field(default=None, alias="templateIds")

class WireContentSection(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    title: str
    body: str
    code_example: Optional[str] = Field(default=None, alias="codeExample")

class WireDefinition(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    term: str
    meaning: str

class WireStudentSignup(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    lrn: str
    name: str
    grade_level: str = Field(alias="gradeLevel")
    section: str
    pin: str

class WireTeacherSignup(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    teacher_id: str = Field(alias="teacherId")
    name: str
    department: str

class WireStudentProgress(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    student_lrn: str = Field(alias="studentLrn")
    section: str
    completed_topic_ids: List[str] = Field(default_factory=list, alias="completedTopicIds")
    quiz_attempts: Dict[str, WireStudentQuizAttempt] = Field(default_factory=dict, alias="quizAttempts")
    quiz_scores: Dict[str, WireQuizScore] = Field(default_factory=dict, alias="quizScores")
    summative_scores: Dict[str, WireSummativeScore] = Field(default_factory=dict, alias="summativeScores")

class WireStudentSummativeResults(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    student_lrn: str = Field(alias="studentLrn")
    section: str
    lesson_id: str = Field(alias="lessonId")
    score: int
    total: int
    percent: int
    passed: bool
    failed_items: List[WireFailedItem] = Field(default_factory=list, alias="failedItems")

class WireQuizAttemptRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    student_lrn: str = Field(alias="studentLrn")
    section: str
    subject: str
    lesson_id: str = Field(alias="lessonId")
    lesson_title: Optional[str] = Field(default=None, alias="lessonTitle")
    topic_id: Optional[str] = Field(default=None, alias="topicId")
    topic_title: Optional[str] = Field(default=None, alias="topicTitle")
    mode: str
    quizzes_per_topic: Optional[int] = Field(default=None, alias="quizzesPerTopic")
    summative_config: Optional[WireSummativeConfig] = Field(default=None, alias="summativeConfig")
    seed: int
    focus_topic_ids: Optional[List[str]] = Field(default=None, alias="focusTopicIds")

class WireRankings(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    section: str
    subject: str
    standings: List[WireStanding] = Field(default_factory=list)

class WireTeacherRemediationMaterial(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    original_topic_id: str = Field(alias="originalTopicId")
    title: str
    content: str
    teacher_notes: str = Field(alias="teacherNotes")
    created_quiz: List[WireQuizQuestion] = Field(default_factory=list, alias="createdQuiz")
    created_summative: Optional[List[WireQuizQuestion]] = Field(default=None, alias="createdSummative")
    publish_date: str = Field(alias="publishDate")
    target_section: str = Field(alias="targetSection")
    chunks: List[WireChunk] = Field(default_factory=list)
    is_published: bool = Field(alias="isPublished")
    subject: Optional[str] = Field(default=None)

class WireTopicContent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    introduction: str
    sections: List[WireContentSection] = Field(default_factory=list)
    definition: Optional[WireDefinition] = Field(default=None)
    key_takeaway: str = Field(alias="keyTakeaway")
    important_note: Optional[str] = Field(default=None, alias="importantNote")

class WireTopic(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    description: str
    reading_time: str = Field(alias="readingTime")
    is_custom_remedial: Optional[bool] = Field(default=None, alias="isCustomRemedial")
    content: WireTopicContent
    quiz: List[WireQuizQuestion] = Field(default_factory=list)

class WireLesson(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str
    description: str
    topics: List[WireTopic] = Field(default_factory=list)
    summative: List[WireQuizQuestion] = Field(default_factory=list)

class WireLessonCatalog(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    subject: str
    lessons: List[WireLesson] = Field(default_factory=list)
