/**
 * Codegen: wire_manifest.json -> Zod schemas (TS) + Pydantic models (Python).
 *
 * The manifest is the single source of truth for the tokenized wire protocol.
 * This script regenerates both validation layers so they can never drift from
 * it (or each other). Run `node protocol/codegen/generate.mjs` to write the
 * files, or `--check` to fail (exit 1) if the on-disk files are stale — used in
 * CI / the test suites.
 *
 * Generated files (DO NOT EDIT BY HAND):
 *   Wave/src/schemas/index.ts
 *   server/wave_api/agents/wire_models.py
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MANIFEST = resolve(__dirname, '../wire_manifest.json');
const TS_OUT = resolve(__dirname, '../../Wave/src/schemas/index.ts');
const PY_OUT = resolve(__dirname, '../../server/wave_api/agents/wire_models.py');

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const { enums, messages, defs } = manifest;

const SCALARS = new Set(['str', 'int', 'bool']);
const cap = (s) => s[0].toUpperCase() + s.slice(1);
const snake = (s) => s.replace(/([A-Z])/g, '_$1').toLowerCase();

/** All message+def types, keyed by name -> {fields}. */
const types = { ...defs, ...messages };

/** Referenced def/message name for a field type, or null for scalar/enum. */
function refOf(t) {
  if (SCALARS.has(t) || t.startsWith('enum:')) return null;
  if (t.startsWith('array:')) return refOf(t.slice(6));
  if (t.startsWith('map:')) return refOf(t.slice(4));
  return t; // ref to a message/def
}

/** Deterministic dependency-first ordering of message+def names. */
function topoOrder() {
  const scan = [...Object.keys(defs), ...Object.keys(messages)];
  const emitted = new Set();
  const order = [];
  let progressed = true;
  while (order.length < scan.length && progressed) {
    progressed = false;
    for (const name of scan) {
      if (emitted.has(name)) continue;
      const deps = types[name].fields.map((f) => refOf(f.t)).filter(Boolean);
      if (deps.every((d) => emitted.has(d))) {
        emitted.add(name);
        order.push(name);
        progressed = true;
      }
    }
  }
  if (order.length !== scan.length) {
    throw new Error('codegen: cyclic or unresolved type refs in manifest');
  }
  return order;
}

/** Enum names referenced by any message/def field (envelope enums excluded). */
function referencedEnums() {
  const seen = new Set();
  for (const name of Object.keys(types)) {
    for (const f of types[name].fields) {
      const m = f.t.match(/enum:(\w+)/);
      if (m) seen.add(m[1]);
    }
  }
  return [...seen].sort();
}

const ORDER = topoOrder();
const REF_ENUMS = referencedEnums();

// ---------------------------------------------------------------- TypeScript
function zodFor(t) {
  if (t === 'str') return 'z.string()';
  if (t === 'int') return 'z.number().int()';
  if (t === 'bool') return 'z.boolean()';
  if (t.startsWith('enum:')) return `${cap(t.slice(5))}Schema`;
  if (t.startsWith('array:')) return `z.array(${zodFor(t.slice(6))})`;
  if (t.startsWith('map:')) return `z.record(z.string(), ${zodFor(t.slice(4))})`;
  return `${t}Schema`;
}

function buildTs() {
  const L = [];
  L.push('/**');
  L.push(' * @license');
  L.push(' * SPDX-License-Identifier: Apache-2.0');
  L.push(' */');
  L.push('');
  L.push('/**');
  L.push(' * GENERATED by protocol/codegen/generate.mjs from protocol/wire_manifest.json.');
  L.push(' * DO NOT EDIT BY HAND. Run `npm run codegen` after changing the manifest.');
  L.push(' *');
  L.push(' * Zod schemas for the canonical wire models. Used to VALIDATE objects decoded');
  L.push(' * from the codec at the sync boundary — a frame off MQTT/LoRa is untrusted');
  L.push(" * input. The UI's internal types stay in ./types.ts.");
  L.push(' */');
  L.push("import { z } from 'zod';");
  L.push('');
  for (const e of REF_ENUMS) {
    const vals = enums[e].map((v) => `'${v}'`).join(', ');
    L.push(`export const ${cap(e)}Schema = z.enum([${vals}]);`);
  }
  L.push('');
  for (const name of ORDER) {
    L.push(`export const ${name}Schema = z.object({`);
    for (const f of types[name].fields) {
      const opt = f.optional ? '.optional()' : '';
      L.push(`  ${f.name}: ${zodFor(f.t)}${opt},`);
    }
    L.push('});');
    L.push('');
  }
  L.push('/** type name -> schema, for validating codec.decode() output by message type. */');
  L.push('export const SCHEMA_BY_TYPE = {');
  for (const name of enums.type) {
    L.push(`  ${name}: ${name}Schema,`);
  }
  L.push('} as const;');
  L.push('');
  const aliases = [
    ['WireStudentProgress', 'StudentProgress'],
    ['WireRankings', 'Rankings'],
    ['WireRemediation', 'TeacherRemediationMaterial'],
    ['WireLessonCatalog', 'LessonCatalog'],
    ['WireLesson', 'Lesson'],
  ];
  for (const [alias, src] of aliases) {
    L.push(`export type ${alias} = z.infer<typeof ${src}Schema>;`);
  }
  return L.join('\n') + '\n';
}

// -------------------------------------------------------------------- Python
function pyType(t) {
  if (t === 'str') return 'str';
  if (t === 'int') return 'int';
  if (t === 'bool') return 'bool';
  if (t.startsWith('enum:')) return 'str';
  if (t.startsWith('array:')) return `List[${pyType(t.slice(6))}]`;
  if (t.startsWith('map:')) return `Dict[str, ${pyType(t.slice(4))}]`;
  return `Wire${t}`;
}

function pyField(f) {
  const name = snake(f.name);
  const needsAlias = name !== f.name;
  const aliasArg = needsAlias ? `alias="${f.name}"` : '';
  const isArray = f.t.startsWith('array:');
  const isMap = f.t.startsWith('map:');
  const base = pyType(f.t);

  if (f.optional) {
    const args = ['default=None', aliasArg].filter(Boolean).join(', ');
    return `    ${name}: Optional[${base}] = Field(${args})`;
  }
  if (isArray) {
    const args = ['default_factory=list', aliasArg].filter(Boolean).join(', ');
    return `    ${name}: ${base} = Field(${args})`;
  }
  if (isMap) {
    const args = ['default_factory=dict', aliasArg].filter(Boolean).join(', ');
    return `    ${name}: ${base} = Field(${args})`;
  }
  if (needsAlias) return `    ${name}: ${base} = Field(alias="${f.name}")`;
  return `    ${name}: ${base}`;
}

function buildPy() {
  const L = [];
  L.push('"""');
  L.push('GENERATED by protocol/codegen/generate.mjs from protocol/wire_manifest.json.');
  L.push('DO NOT EDIT BY HAND. Run `npm run codegen` after changing the manifest.');
  L.push('');
  L.push('Pydantic mirrors of the canonical wire models. Field aliases are camelCase');
  L.push('so `.model_dump(by_alias=True)` round-trips cleanly through');
  L.push('`codec.encode(...)`. Agent-internal shapes (diagnosis, evaluator output,');
  L.push('letter-keyed options) are deliberately NOT mirrored here — they never reach');
  L.push('MQTT/LoRa.');
  L.push('"""');
  L.push('from typing import Dict, List, Optional');
  L.push('');
  L.push('from pydantic import BaseModel, ConfigDict, Field');
  L.push('');
  for (const name of ORDER) {
    L.push('');
    L.push(`class Wire${name}(BaseModel):`);
    L.push('    model_config = ConfigDict(populate_by_name=True)');
    L.push('');
    for (const f of types[name].fields) L.push(pyField(f));
  }
  return L.join('\n') + '\n';
}

// ----------------------------------------------------------------- run/check
const outputs = [
  [TS_OUT, buildTs()],
  [PY_OUT, buildPy()],
];
const check = process.argv.includes('--check');
let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      /* missing file counts as stale */
    }
    // Normalize newlines so the check is robust to git autocrlf on checkout.
    const norm = (s) => s.replace(/\r\n/g, '\n');
    if (norm(current) !== norm(content)) {
      console.error(`codegen: STALE -> ${path}`);
      stale = true;
    }
  } else {
    writeFileSync(path, content);
    console.log(`codegen: wrote ${path}`);
  }
}
if (check) {
  if (stale) {
    console.error('codegen: run `npm run codegen` to regenerate.');
    process.exit(1);
  }
  console.log('codegen: up to date.');
}
